832203305 - work2
west2-online-reserve/collection-android pull request #19
Opened 2023-11-01 15:46 UTC by Archer-Min

2023-11-03 16:53 UTC, klxiaoniu requested changes

2023-11-03 16:53 UTC, klxiaoniu commented on work2/Archer-Min/Animal.java
这个空行怎么忽多忽少嘞，看着会有点不舒服

2023-11-03 16:53 UTC, klxiaoniu commented on work2/Archer-Min/Customer.java
> +    private int times;
变量定义放在开头更清晰

2023-11-03 16:53 UTC, klxiaoniu commented on work2/Archer-Min/Customer.java
> +    public void setTimes(int times) {
这里用set还是自增更好？

2023-11-03 16:53 UTC, klxiaoniu commented on work2/Archer-Min/MyAnimalShop.java
> +        }catch (InsufficientBalanceException e){
抛出异常在具体方法实现中，捕获异常应该主要做在主函数（测试函数）中，这样更有利于暴露调用方法出现的问题。像这样自己抛出然后马上捕获，是不是没感觉到它有啥意义？这样做还不如直接用if-else了

2023-11-03 16:53 UTC, klxiaoniu commented on work2/Archer-Min/MyAnimalShop.java
> +    private double remainder0;
这两个变量啥意思？不能一眼明确

2023-11-04 13:26 UTC, Archer-Min commented
完成一些修改

2023-11-05 15:22 UTC, merged