172209029 - work2
west2-online-reserve/collection-android pull request #23
Opened 2023-11-06 11:01 UTC by wanandaodao

完成了作业的所有内容

2023-11-06 14:39 UTC, klxiaoniu requested changes
对题目的理解有点不周到，需要再完善一下

2023-11-06 14:39 UTC, klxiaoniu commented on work2/wanandaodao/ChineseRuralDog.java
> +    boolean isVaccineInjected;
作用域修饰符呢？

2023-11-06 14:39 UTC, klxiaoniu commented on work2/wanandaodao/Customer.java
> +    public String name;
这些变量的作用域需要修改一下，作用域最小化原则，是最安全健壮的，更何况已经提供getter和setter，不需要设为public。其他地方也同理

2023-11-06 14:39 UTC, klxiaoniu commented on work2/wanandaodao/MyAnimalShop.java
> +        customerList.add(cus);
如果是重复顾客，会重复添加？

2023-11-06 14:39 UTC, klxiaoniu commented on work2/wanandaodao/MyAnimalShop.java
> +        customerList.add(cus);
顾客到店次数、最近到店时间没有统计吗

2023-11-06 15:29 UTC, wanandaodao reviewed
更改了成员变量的作用域，Debug了treatCustomer方法并且进行了相应的测试

2023-11-06 15:29 UTC, wanandaodao commented on work2/wanandaodao/MyAnimalShop.java
> +        customerList.add(cus);
已debug

2023-11-06 15:31 UTC, wanandaodao commented on work2/wanandaodao/Customer.java
> +    public String name;
已更改

2023-11-06 17:30 UTC, wanandaodao reviewed
完善了封装，根据只需自增需求更改了Customer类setter方法的函数名

2023-11-07 02:32 UTC, klxiaoniu commented
Customer和Animal不是一对一的关系，Customer类中不应该存在animal变量

2023-11-07 03:11 UTC, wanandaodao reviewed
已修改

2023-11-07 03:12 UTC, wanandaodao commented
> Customer和Animal不是一对一的关系，Customer类中不应该存在animal变量

已修改

2023-11-07 04:40 UTC, merged